import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'

import { CarInfoCard, Filters } from '../molecules'
import VehicleService from '../services/vehicleService'
import { FilterTypes } from '../molecules/Filters/Filters.types'
import { Vehicle } from '../types/Vehicle'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [vehicleList, setVehicleList] = useState<Vehicle[]>([])
  const [filters, setFilters] = useState({})

  useEffect(() => {
    fetchData()
  }, [filters])

  const fetchData = async () => {
    const response = await VehicleService.fetchRecords(filters as FilterTypes)
    setVehicleList(response.records)
  }

  const onFilterChange = async (filters: FilterTypes) => {
    try {
      setFilters(filters)
    } catch(err) {}
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/icomoon/style.css" />
      </Head>

      <main className={styles.main}>
        <div className={styles.main_container}>
          <div className={styles.filter_wrapper}>
            <Filters onFilterChange={onFilterChange}/>
          </div>
          <div className={styles.grid}>
            {
              vehicleList .map(record => {
                return <CarInfoCard key={record.vehicleId} record={record} />
              })
            }

            {
              !vehicleList.length && (
                <h3>No Cars found</h3>
              )
            }
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
